blank_issues_enabled: true
contact_links:
  - name: 🤔 Long questions or ideas?
    url: https://github.com/Fire-Oceann/CS-Space/discussions
    about: Ask long-form questions and discuss ideas.
  - name: 💬 Discord Community Chat
    url: https://discord.gg/bYWVWrDkCU
    about: Ask quick questions or chat on the `CS-SPCAE` community Discord server.